version: '3'
services:
  nextjs:
    build:
      context: .
      args:
        - NEXT_PUBLIC_SHEET_URL=${NEXT_PUBLIC_SHEET_URL}
    environment:
      - NEXT_PUBLIC_SHEET_URL=${NEXT_PUBLIC_SHEET_URL}
    ports:
      - '3000:3000'
